[package]
name = "pigtail"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[[bin]]
name = "pigtail"
path = "src/main.rs"

[dependencies]
iron = "0.5"
router = "0.5"
logger = "0.3"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
hybrid-clocks = { version = "^0.3.3", features = ["serde"] }
uuid = {version = "0.4", features=["use_std","v4","serde"]}

url = "*"
postgres = {features=["with-uuid","with-serde_json"], version="0.13"}

potboiler_common = { path = "../potboiler_common" }

r2d2 = "0.7"
r2d2_postgres = "0.11"
persistent = "0.3"

log = "*"
log4rs = {version = ">= 0.4, <0.7", features=["yaml_format"]}

hyper = "0.10"

lazy_static = "0.2"
time = "0.1"
