sudo: required
services:
  - docker

language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo
env:
  - PROJECT=potboiler_common
  - PROJECT=core
  - PROJECT=kv
  - PROJECT=pigtail
  - PROJECT=docker
script: ./build.sh

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true