sudo: required
services:
  - docker

language: rust
rust:
  - 1.24.0
cache: cargo
env:
  - PROJECT=potboiler_common
  - PROJECT=core
  - PROJECT=kv
  - PROJECT=pigtail
  - PROJECT=docker
script: ./build.sh
