sudo: false

dist: xenial

services:
  - docker

language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  cargo: true
  directories:
    - target/rustfmt

env:
  global:
    - CARGO_TARGET_DIR=./target/rustfmt
  matrix:
    - PROJECT=potboiler_common
    - PROJECT=core
    - PROJECT=kv
    - PROJECT=pigtail
    - PROJECT=docker
before_script:
  - rustup component add rustfmt-preview
script: ./build.sh

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
  - rust: beta
    env: PROJECT=docker
  - rust: nightly
    env: PROJECT=docker