[package]
name = "potboiler"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[[bin]]
name = "potboiler"

[dependencies]
hybrid-clocks = { version = "0.3", features = ["serde"] }
uuid = {version = "^0.4", features=["v4","serde"]}
log = "*"
log4rs = {version = ">= 0.4, <0.7", features=["yaml_format"]}

iron = "0.5"
plugin = "0.2"
router = "0.5"
logger = "0.3"
serde = "0.9"
serde_json = "0.9"
urlencoded = "0.5"

potboiler_common = { path = "../potboiler_common" }

url = "*"
postgres = {features=["with-uuid","with-serde_json"], version="0.13"}
schemamama = "0.2"
schemamama_postgres = "=0.2.0"

r2d2 = "0.7"
r2d2_postgres = "0.11"
persistent = "0.3"

hyper = "0.10"
resolve = "0.1.2"