[package]
name = "serial_test"
version = "0.1.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
antidote = "1.0"
lazy_static = "1.2"
quote = "0.6"