[package]
name = "kv"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[[bin]]
name = "kv"
path = "src/main.rs"

[dependencies]
iron = "0.6"
router = "0.6"
logger = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hybrid-clocks = { version = "^0.3.4", features = ["serde"] }
uuid = {version = "^0.5", features=["use_std","v4","serde"]}
mime = "0.2"

url = "*"
postgres = {features=["with-uuid","with-serde_json"], version="0.15"}

potboiler_common = { path = "../potboiler_common" }

r2d2 = "0.8"
r2d2_postgres = "0.14"
persistent = "0.4"

log = "*"
log4rs = {version = ">= 0.4, <0.7", features=["yaml_format"]}

hyper = "0.10"

lazy_static = "0.2"
