[package]
name = "kv"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[[bin]]
name = "kv"

[dependencies]
iron = "*"
router = "*"
logger = "*"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
hybrid-clocks = { git = "https://github.com/palfrey/hybrid-clocks.git", branch = "serde-0.9", features = ["serde"] }
uuid = {version = "*", features=["use_std","v4","serde"]}
mime = "*"

url = "*"
postgres = {features=["with-uuid","with-serde_json"], version=">=0.13.5"}

potboiler_common = { path = "../potboiler_common" }

r2d2 = "*"
r2d2_postgres = "*"
persistent = "*"

log = "*"
log4rs = {version = ">= 0.4", features=["yaml_format"]}

hyper = "*"

lazy_static = "0.1.*"
