[package]
name = "potboiler_common"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
iron = "0.6"
uuid = {version = "0.6", features=["use_std","v4","serde"]}
r2d2 = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "*"
hybrid-clocks = { git = "https://github.com/palfrey/hybrid-clocks/", branch = "serde-1.0", features = ["serde"] }
router = "0.5"
error-chain = "0.11.0"

diesel = { version = "1.0", features = ["postgres", "uuid", "serde_json"] }
r2d2-diesel = "1.0"

[lib]
name = "potboiler_common"
path = "src/lib.rs"
