[package]
name = "potboiler_common"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
iron = "0.5"
uuid = {version = "0.4", features=["use_std","v4","serde"]}
postgres = {features=["with-uuid","with-serde_json"], version="0.13"}
r2d2 = "0.7"
r2d2_postgres = "0.11"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
log = "*"
hybrid-clocks = { version = "^0.3.3", features = ["serde"] }
router = "0.5"

[lib]
name = "potboiler_common"
