[package]
name = "potboiler_common"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
iron = "*"
uuid = {version = "*", features=["use_std","v4","serde"]}
postgres = {features=["with-uuid","with-serde_json"], version=">=0.13.5"}
r2d2 = "*"
r2d2_postgres = "*"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
log = "*"
hybrid-clocks = "0.3.3"
router = "0.5"

[lib]
name = "potboiler_common"
